### ISSUE TITLE
Listing tracks in v3 where track spawn location is not loaded causes 500

### ISSUE THREAD

**Issue by Makkuusen** [JustBru00/TimingSystemRESTApi#17]
![image](https://github.com/JustBru00/TimingSystemRESTApi/assets/45494209/54869431-6e35-4586-9b7e-f495729bd5e9)

**Comment by JustBru00** [comment]
I will need to add a check to make sure the world is loaded before serialization.
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Location.html#isWorldLoaded()

**Comment by P-333** [comment]
I would just do
`obj.addProperty("world_name", loc.isWorldLoaded() ? loc.getWorld().getName() : "null");`
 on the serializeLocation object
